### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Clueless-AI** [trcrsired/LookingForGroup#1]
Hello, 
1st of all I wanted to thank you for making this great addon, I was so desperate to find an addon that show an expanded window for LFG  that shows way more results than the default tiny window with a scroll bar. 
When I first downloaded the addon I noticed some stuffs that I had added to the default LFG to make it easier to navigate were missing, for example an addon called Windtools allows me to filter the LFG by dungeons and I can make a research with one or two or even more dungeons for that specific season which I couldn't do with your addon, and Windtools also show specialization icons for the party members is each available party in the LFG but your addon only shows THDDD letters colored with class colors which is kinda hard to read and spot 
I really hope you guys can make those improvements/addition to your addon cause its an addon that I can see myself using forever and thanks a lot in advance

**Comment by trcrsired** [comment]
looks like the old code that removed for details showing in the tooltip should be brought back.

**Comment by trcrsired** [comment]
you want to search multiple dungeons. You can add multiple activities search in the scroll bar in the find

**Comment by Clueless-AI** [comment]
> looks like the old code that removed for details showing in the tooltip should be brought back.

Hello, thanks for the quick reply. Does that mean that with that coming back we will be able to see the classes/specs in each party by mouseovering them ?


> you want to search multiple dungeons. You can add multiple activities search in the scroll bar in the find

I'll def try that tonight thanks

**Comment by trcrsired** [comment]
can you have a look at it? is that what you want?

**Comment by trcrsired** [comment]
![image](https://github.com/trcrsired/LookingForGroup/assets/100043421/e2883c8f-ac89-4079-b9e3-05fa6b87b41c)

**Comment by Clueless-AI** [comment]
![image](https://github.com/trcrsired/LookingForGroup/assets/86970171/efb7743f-d186-4eb2-84b9-98dbe31430c3)
![image](https://github.com/trcrsired/LookingForGroup/assets/86970171/8c636e5c-df6c-4971-9712-9520956dfda5)
 basically something like this if its possible cause knowing the Specialization of people is so important before joining any party. Dunno if Windtools affects the tooltips of your addon too or not. I'll try it and see if it works

**Comment by trcrsired** [comment]
looks like C_LFGList.GetSearchResultMemberInfo now returns a spec as the 4th parameter which did not exist when lfg was written. going to add it.

**Comment by Clueless-AI** [comment]
> looks like C_LFGList.GetSearchResultMemberInfo now returns a spec as the 4th parameter which did not exist when lfg was written. going to add it.

Thanks a lot ^^ thats literally what  wanted

**Comment by trcrsired** [comment]
You need to give me some time, it is not a small change plus i need to change other part that would interact with it

**Comment by trcrsired** [comment]
![I6QXPU160VAVO3PF{V_~ PT](https://github.com/trcrsired/LookingForGroup/assets/100043421/63cd9e85-52f9-495e-b8b4-dbeecee35e07)

**Comment by trcrsired** [comment]
is this ok now?

**Comment by trcrsired** [comment]
needs Lfg 3327+

**Comment by trcrsired** [comment]
hello??

**Comment by Clueless-AI** [comment]
> hello??

Hello, sorry been away from some time.
Ye that is def what I need its perfect, thank you
